---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: pageviews
  namespace: confluent
spec:
  class: "io.confluent.kafka.connect.datagen.DatagenConnector"
  taskMax: 4
  connectClusterRef:
    name: connect
  configs:
    kafka.topic: "pageviews"
    quickstart: "pageviews"
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter.schemas.enable: "false"
    max.interval: "100"
    iterations: "10000000"
    bootstrap.servers: "kafka.aks.shapeblock.xyz:443"
    security.protocol: "SSL"
    ssl.truststore.location: "${file:/mnt/secrets/kafka-certs/truststore}"
    ssl.truststore.password: "mystorepassword"
    ssl.truststore.type: "PKCS12"
